server:
  port: 8083

spring:
  application:
    name: coffee-status
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: kosa01
    password: 1234

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.coffeestatus.vo

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true



